src/helpers/getDomain.js

sopra-fs24-group07/admin#3 
- todo done

inserted server domain

---

src/components/popups/CreateTask.tsx
src/components/ui/ColumnContainer.tsx
src/components/ui/KanbanBoard.tsx
src/components/ui/TaskCard.tsx
src/components/views/TeamDashboard.tsx

Assignee: Monti934
Reviewer: B1s9l
- \[x\] are there any code smells?
- \[x\] did pipeline pass?
- \[x\] is the code well documented?

Tde task creation to dev

---

src/components/popups/CreateTask.tsx
src/components/popups/InspectTask.tsx
src/components/ui/TaskCard.tsx
src/components/views/TeamDashboard.tsx
src/styles/ui/TaskCard.scss

Task Details, Task Edit and clean-up for main merge

---

src/components/popups/CreateTeam.tsx
src/components/popups/Profile.tsx
src/components/popups/ProfileMenu.tsx
src/components/popups/ProfileSettings.tsx
src/components/views/Login.tsx
src/components/views/Registration.tsx
src/components/views/TeamsOverview.tsx
src/styles/_theme.scss
src/styles/popups/ProfileMenu.scss
src/types.ts

I finished:
- Create team UI form #5
- Profile view #26
As discussed:
- All buttons are functional
- Input validation and error handling where implemented is consistent with REST specs
ToDo:

Issues #5 and #26 and discussed changes

---

.github/pull_request_template.md
.github/workflows/build-test.yml

- pipeline to warn if npm run build is not working

Sgr pipeline eslint

---

src/components/popups/CreateTeam.tsx
src/components/views/Login.tsx
src/components/views/Registration.tsx

-Change to doublequotes
-added lines before return statements

quickfix eslint for npm build

---

src/components/popups/CreateTask.tsx
src/components/popups/CreateTeam.tsx
src/components/popups/InspectTask.tsx
src/components/popups/Profile.tsx
src/components/popups/ProfileMenu.tsx
src/components/popups/ProfileSettings.tsx
src/components/routing/routeProtectors/GameGuard.js
src/components/routing/routeProtectors/LoginGuard.js
src/components/ui/TaskCard.tsx
src/components/views/Login.tsx
src/components/views/Registration.tsx
src/components/views/TeamDashboard.tsx
src/components/views/TeamsOverview.tsx

- changed and tested for functionality
- as discussed in meeting 
- merge into active branches locally

change sessionStorage to localStorage in all files

---

gitmessage.txt
src/components/popups/CreateTask.tsx
src/components/popups/TeamSetting.tsx
src/components/routing/routers/AppRouter.js
src/components/views/InviteLanding.tsx
src/components/views/Login.tsx
src/components/views/Registration.tsx
src/components/views/TeamDashboard.tsx
src/styles/popups/TeamSetting.scss
src/styles/views/InviteLanding.scss

Team Invitation done

---

src/components/views/Login.tsx
src/components/views/Registration.tsx

-get invite functionality in login/register back

manually fix merge issues

---

package-lock.json
package.json
src/components/ui/VoiceChat.tsx
src/styles/ui/VoiceChat.scss

- VoiceChat component is ready
- can be implemented in TeamDashboard when session is active

Implemented VoiceChat

---

src/components/popups/CreateTask.tsx
src/components/popups/InspectTask.tsx
src/components/popups/TeamSetting.tsx
src/components/ui/TaskCard.tsx
src/components/views/TeamDashboard.tsx

- merged local to resolve conflicts

Task Edit (also KanbanBoard), Activate Team-Leave, VoiceChat

---

src/components/popups/ProfileSettings.tsx

sopra-fs24-group07/sopra-fs24-group-07-client/issues/ -set errors and password as empty string

remove errors on opening Settings

---

src/components/ui/CommentCard.tsx
src/components/ui/Comments.tsx
src/styles/ui/CommentCard.scss

- The creation Date of a comment is now shown in the bottom right corner

Comments with creation Date

---

src/components/ui/Spinner.tsx
src/components/ui/VoiceChat.tsx
src/components/views/Header.tsx

- Back to teams button will disconnect user from voice chat
- breakout rooms for seperate tasks with the same name will now create seperate voice channels
- on joining a channel, a loading screen is shown which prohibits user input to avoid errors (e.g. for long response time of agora or wait to allow microphone usage)
- setting a Task to In_Session_Done will now remove the corresponding voicechat from the list. However the users will not be kicked out, a room is closed when the last member leaves. On reactivating the task, the voice channel will be reinstantiated aswell (added a TODO comment for pusher for this and need the updated pusher without location.reload to work)

VoiceChannel fixes

---

src/components/views/TeamDashboard.tsx

fix issue with userId as string for redirecting if not in team

---

src/components/ui/VoiceChat.tsx
src/components/views/TeamDashboard.tsx
src/styles/ui/VoiceChat.scss

- Mute button is now shown under all members to avoid accidental wrong inputs
- Voice Chat Headline in Dashboard
- long usernames don't overflow anymoer
- all members leave the voice chats when session ends

Voice Chat fixes/styling

---

src/components/popups/ConfirmDelete.tsx
src/components/popups/CreateTask.tsx
src/components/popups/CreateTeam.tsx
src/components/popups/InspectTask.tsx
src/components/popups/ProfileSettings.tsx
src/styles/popups/ProfileMenu.scss

Also added the styling to the profile menu .scss

Added disclaimer to delete profile page

---

src/components/ui/SessionTaskBoard.tsx
src/components/views/ProgressField.tsx
src/components/views/TeamDashboard.tsx

Issue #21
Changed the implementation of checked tasks switching to status DONE when session is ended

Fixed the infinite recursion for task status

---

src/components/views/ProgressField.tsx

Finding progress bar bug

---

src/components/popups/InspectTask.tsx

sopra-fs24-group07/sopra-fs24-group-07-server/issues/150

removed 2 location.reloads in inspeczTask

---

src/components/popups/TeamSetting.tsx
src/components/ui/VoiceChat.tsx

- added Event Dispatch and Event Listener

user leaves voiceChannel when leaving team

---

src/components/popups/CreateTeam.tsx

Assignee:
- \[x\] deactivated things not needed? (e.g. other features which only were prepared)
- \[x\] alerts that this is todo?
- \[x\] test run localhost?
Reviewer:

Quickfix for never ending loading spinner on create team error

---

src/components/popups/CreateTask.tsx
src/components/popups/CreateTeam.tsx
src/components/popups/InspectTask.tsx

taks infinite load bugfix

---

src/components/popups/ProfileSettings.tsx
src/components/views/Registration.tsx

Assignee:
- \[x\] deactivated things not needed? (e.g. other features which only were prepared)
- \[x\] alerts that this is todo?
- \[x\] test run localhost?
Reviewer:

Input validation for all fields on register and edit profile

---

package-lock.json
package.json
src/components/ui/ColumnContainer.tsx
src/components/ui/KanbanBoard.tsx
src/components/ui/TaskCard.tsx
src/styles/ui/TaskCard.scss

Assignee:
- \[ /] documentation added / updated?
Reviewer:

Tde drag drop

---

src/components/views/TeamsOverview.tsx

Showing team description when hovering over a team

---

package-lock.json
package.json
src/components/popups/ConfirmDelete.tsx
src/components/popups/CreateTask.tsx
src/components/popups/CreateTeam.tsx
src/components/popups/InspectTask.tsx
src/components/popups/Profile.tsx
src/components/popups/ProfileMenu.tsx
src/components/popups/ProfileSettings.tsx
src/components/popups/SessionHistory.tsx
src/components/popups/TeamSetting.tsx
src/components/ui/CommentCard.tsx
src/components/ui/Comments.tsx
src/components/ui/IconButton.tsx
src/components/ui/TaskCard.tsx
src/components/ui/VoiceChat.tsx
src/components/views/Header.tsx
src/components/views/Login.tsx
src/components/views/Registration.tsx
src/components/views/TeamDashboard.tsx
src/styles/_theme.scss
src/styles/popups/CreateTeam.scss
src/styles/popups/ProfileMenu.scss
src/styles/popups/SessionHistory.scss
src/styles/ui/IconButton.scss
src/styles/ui/TaskCard.scss
src/styles/ui/VoiceChat.scss
src/styles/views/TeamDashboard.scss

Icons for whole application and Profile Menu redo 

---

src/components/views/Login.tsx
src/components/views/Registration.tsx
src/styles/popups/SessionHistory.scss
src/styles/ui/ColumnContainer.scss

Thin Scroll Bars

---

src/components/popups/CreateTask.tsx
src/components/popups/CreateTeam.tsx
src/components/popups/InspectTask.tsx
src/components/popups/ProfileSettings.tsx
src/components/popups/TeamSetting.tsx
src/components/ui/Comments.tsx
src/components/views/Registration.tsx
src/styles/views/TeamsOverview.scss

Inout #110
Assignee:
- \[x\] deactivated things not needed? (e.g. other features which only were prepared)
- \[x\] alerts that this is todo?
- \[x\] test run localhost?
Reviewer:

Updated input length for various items according to backend specs

---

src/components/ui/KanbanBoard.tsx

sopra-fs24-group07/sopra-fs24-group-07-client/issues/130 -
Assignee:
Reviewer:

Fix Drag Drop bug

---

src/components/ui/VoiceChat.tsx
src/components/views/TeamDashboard.tsx

Task Query

---

src/components/views/TeamDashboard.tsx

sopra-fs24-group07/sopra-fs24-group-07-client/issues/ -
Assignee:
Reviewer:

Query Quick Fix

---

src/components/popups/Profile.tsx
src/styles/popups/InspectTask.scss

Logout button was invisible when no user data was present

---

src/components/views/TeamDashboard.tsx

sopra-fs24-group07/sopra-fs24-group-07-client/issues/109
Assignee:
Reviewer:
n/a

remove space in url for query

---

src/components/popups/CreateTask.tsx
src/components/popups/InspectTask.tsx
src/components/popups/TeamMembers.tsx
src/components/ui/EmailInput.tsx
src/components/views/Registration.tsx
src/styles/popups/CreateTeam.scss
src/styles/popups/InspectTask.scss
src/styles/popups/Notification.scss
src/styles/popups/TeamSetting.scss
src/styles/ui/IconButton.scss
src/styles/views/Login.scss
src/styles/views/Register.scss
src/styles/views/TeamsOverview.scss

Issue #99
Assignee:
Reviewer:
- \[x]tested manually all features and edge cases?

Notification container + createteam button styling

---

src/components/popups/CreateTeam.tsx
src/components/popups/TeamSetting.tsx

Improved error handling for AI description generation

---

src/components/popups/CreateTeam.tsx
src/components/popups/TeamSetting.tsx

Quickfix: Changed the faulty message string

---

src/components/popups/CreateTeam.tsx
src/components/popups/TeamSetting.tsx

Bfu ai quickfix

---

src/components/popups/CreateTeam.tsx

Clear input when aborted early

---

src/components/views/TeamDashboard.tsx
src/styles/popups/Notification.scss

sopra-fs24-group07/sopra-fs24-group-07-client/issues/141 -also made notify to 6em
Assignee:
Reviewer:

fix bug and add notify to Dashboard for wrong team

---

src/components/ui/VoiceChat.tsx

Agora Token

---

src/components/popups/Notification.tsx
src/styles/popups/Notification.scss

Notifs now slide in

---

src/components/popups/TeamMembers.tsx

The member list in the popup now updates with a change

---

src/components/ui/Button.tsx
src/components/views/TeamsOverview.tsx
src/styles/ui/Button.scss

Teams session status is now shown on overview page

---

src/components/ui/IconButton.tsx
src/components/ui/TaskCard.tsx
src/styles/ui/TaskCard.scss

New Drag and Drop styling/functionality

---

gitmessage.txt
src/components/ui/VoiceChat.tsx

Voice Chat error messages

---

src/assets/faqs.tsx
src/components/popups/FAQ.tsx
src/components/popups/FAQEntity.tsx
src/components/popups/Profile.tsx
src/components/popups/Tutorial.tsx
src/components/routing/routers/GameRouter.js
src/components/ui/Comments.tsx
src/components/ui/FormField.tsx
src/components/views/Header.tsx
src/components/views/TeamsOverview.tsx
src/styles/popups/FAQS.scss
src/styles/popups/TeamSetting.scss
src/styles/popups/Tutorial.scss
src/styles/ui/Button.scss
src/styles/ui/Comments.scss
src/styles/ui/FormField.scss
src/styles/views/Header.scss

Improved faq on new branch for convenience

---

src/components/popups/InspectTask.tsx
src/components/ui/ColumnContainer.tsx
src/components/ui/KanbanBoard.tsx
src/components/ui/TaskCard.tsx
src/styles/popups/InspectTask.scss

Fix Task Inspect Bugs

---

src/components/popups/TeamSetting.tsx
src/styles/popups/CreateTeam.scss
src/styles/popups/InspectTask.scss

Teamsettings quickfix

---

src/components/popups/Tutorial.tsx

Lines for tutorial added for describing voicechat

---

src/components/popups/CreateTeam.tsx
src/components/popups/TeamSetting.tsx
src/components/views/StatusComponent.tsx
src/components/views/TeamsOverview.tsx

Bfu button disable to minimize spam or whatever :))

---

src/assets/faqs.tsx
src/components/popups/FAQ.tsx
src/components/ui/Button.tsx
src/components/views/ProgressField.tsx
src/components/views/TeamDashboard.tsx
src/components/views/TeamsOverview.tsx
src/styles/views/TeamsOverview.scss

All bugfixes except tooltips

---

src/styles/views/TeamsOverview.scss

Pre-commit

---

src/components/popups/CreateTeam.tsx
src/components/popups/EasterEggPopup.tsx
src/components/popups/FAQ.tsx
src/components/popups/ProfileSettings.tsx
src/components/popups/TeamMembers.tsx
src/components/popups/TeamSetting.tsx
src/components/ui/ColumnContainer.tsx
src/components/ui/Comments.tsx
src/components/views/Login.tsx
src/components/views/Registration.tsx
src/components/views/StatusComponent.tsx
src/components/views/TeamDashboard.tsx
src/components/views/TeamsOverview.tsx
src/helpers/api.js

Assignee:
Reviewer:
- \[x\] correct branch?

Submit with Enter, Remove/Replace console.logs

---

src/components/popups/CreateTeam.tsx

add title to ai button fo more understandability

---

src/styles/popups/FAQS.scss

Assignee:
Reviewer:
- \[x\] correct branch?
- \[x\] are there any code smells?
- \[x\] did pipeline pass?
- \[ \] ~~is the code well documented?~~

Increased margin for error message

---

src/components/views/TeamsOverview.tsx
src/styles/views/TeamsOverview.scss

Assignee:
Reviewer:
- \[x\] correct branch?
- \[x\] are there any code smells?
- \[x\] did pipeline pass?
- \[x\] is the code well documented?

Bfu tooltips new

---

src/components/popups/EasterEggPopup.tsx

Updated URLS for sven & alihan

---

src/components/views/Landing.tsx

Bfu warmup

---

src/components/popups/ProfileSettings.tsx
src/components/views/Registration.tsx

Error for register and edit user

---

src/assets/faqs.tsx
src/components/views/Registration.tsx

Added 1 faqs

---

src/assets/faqs.tsx
src/components/views/Login.tsx
src/components/views/Registration.tsx

Bfu error quickfix

---

src/assets/faqs.tsx

Assignee:
Reviewer:
- \[x\] correct branch?
- \[x\] are there any code smells?
- \[x\] did pipeline pass?

Adding missing faq
